### ISSUE TITLE
SS019 should add using statement

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/SharpSource#149]
![image](https://user-images.githubusercontent.com/2777107/188521306-841d3b9f-ce26-47de-b6ea-ecf3ca562f70.png)

Notice how `ArgumentException` is in black -- indicating it is an unresolved symbol.

**Comment by piyushkumargithub** [comment]
It will be my first open source contribution can I try this one?

**Comment by Vannevelj** [comment]
@piyushkumargithub definitely, go for it 👍 You'll want to use this handy extension method which does most of the heavy lifting for you: https://github.com/Vannevelj/SharpSource/blob/f95a64669619fcaaa0852028cca928f39288d3af/SharpSource/SharpSource/Utilities/Extensions.cs#L331

If you're unsure of anything or you don't know where to start, let me know and I'll gladly help you move forward

**Comment by piyushkumargithub** [comment]
yes, please for me the code base is overwhelming 🥲. How to start? I have worked on stuff like asp.net core web api before. If that  is not enough please tell me 🥲 don't want to waste your time.

**Comment by Vannevelj** [comment]
I have written up a few basic notes here on contributing in general: https://github.com/Vannevelj/SharpSource/blob/master/CONTRIBUTING.md#how-do-i-create-a-new-analyzer

Some knowledge of C# is definitely required to work on this so having some ASP.NET experience is great 👍 
For this particular issue, you'd have to do a few things:
1. Create a unit test to demonstrate the failure scenario. That means copying a basic unit test for the analyzer in question (SS019, SwitchIsMissingDefaultLabel) and modifying it. For this issue, you can take [this test](https://github.com/Vannevelj/SharpSource/blob/f95a64669619fcaaa0852028cca928f39288d3af/SharpSource/SharpSource.Test/SwitchIsMissingDefaultLabelTests.cs#L16-L73) and remove the `using System;` at the top of the `original` variable.
2. Now you should have a unit test that fails because your actual output won't match the expected output
3. To fix the issue, we need to generate the correct code. Head into the [SwitchIsMissingDefaultCodeFix](https://github.com/Vannevelj/SharpSource/blob/f95a64669619fcaaa0852028cca928f39288d3af/SharpSource/SharpSource.CodeFixes/Diagnostics/SwitchIsMissingDefaultLabelCodeFix.cs#L44-L58) and change it so that it also adds the using statement if it is missing.

However! I noticed that while I looked at this that this functionality actually already works and there is even a unit test for this particular behaviour: https://github.com/Vannevelj/SharpSource/blob/f95a64669619fcaaa0852028cca928f39288d3af/SharpSource/SharpSource.Test/SwitchIsMissingDefaultLabelTests.cs#L389

For that reason I'm going to close this issue but please do feel free to take a look and see if there is anything else you would like to tackle 🙏 

NB: if you are interested in writing Roslyn analyzers in particular, I recommend reading through this paper I wrote years ago. It should give you a pretty good idea of what Roslyn is exactly and what these analyzers can do. https://www.dropbox.com/s/rc9edahndlog0je/MainPaper.pdf?dl=0

**Comment by piyushkumargithub** [comment]
Thanks for explanation. Ok I understood a bit. Will sure go through your paper first and then try to tackle some issues😊.
