### ISSUE TITLE
`AddUsingStatementIfMissing` shouldn't be used

### ISSUE THREAD

**Issue by Youssef1313** [Vannevelj/SharpSource#231]
This method syntactically looks at using statements in the current tree.

This doesn't take into account the following:

- global usings
- User preferences regarding `using` order
- User preferences regarding `using` placement (inside/outside namespace)

This should be removed, and `Simplifier.AddImportsAnnotation` should be used.

https://github.com/dotnet/roslyn/blob/2a383c15229f744db4c59856697cdad5e2820a0e/src/Workspaces/Core/Portable/Simplification/Simplifier.cs#L53-L57

**Comment by Vannevelj** [comment]
I've give this a try but it doesn't appear to do anything. Am I not using it correctly? https://github.com/Vannevelj/SharpSource/pull/276/files

**Comment by Youssef1313** [comment]
@Vannevelj It won't work on its own. There have to be a symbol annotation as well.

A symbol annotation can come from some `SyntaxGenerator` methods that takes symbols, such as `SyntaxGenerator.TypeExpression(ITypeSymbol)` method, or by manually adding a symbol annotation.

Currently, `SymbolAnnotation` is internal to Roslyn, but you can easily replicate its logic:

```csharp
using System.Collections.Immutable;
using System.Linq;

namespace Microsoft.CodeAnalysis.Simplification
{
    /// <summary>
    /// An annotation that holds onto information about a type or namespace symbol.
    /// </summary>
    internal static class SymbolAnnotation
    {
        private const string Kind = "SymbolId";

        public static SyntaxAnnotation Create(ISymbol symbol)
            => Create(DocumentationCommentId.CreateReferenceId(symbol));

        public static SyntaxAnnotation Create(string referenceId)
            => new(Kind, referenceId);
    }
}
```

**Comment by Vannevelj** [comment]
I'm not quite sure how I'm supposed to use this. I've attempted it in [`7443070` (#276)](https://github.com/Vannevelj/SharpSource/pull/276/commits/744307016a4c1c502f2ad7408c13f45dc5571b54) but I guess I'm still using it incorrectly? I had a look through the Roslyn repos but it doesn't appear to be widely used in the same context as I'm using it
