### ISSUE TITLE
SS054 : Wrong filename for md document

### ISSUE THREAD

**Issue by jmguazzo** [Vannevelj/SharpSource#317]
The name of the document has the extension ".md.md"
https://github.com/Vannevelj/SharpSource/blob/master/docs/SS054-NewtonsoftMixedWithSystemTextJson.md.md

The link in the [code](https://github.com/Vannevelj/SharpSource/blob/master/SharpSource/SharpSource/Diagnostics/NewtonsoftMixedWithSystemTextJsonAnalyzer.cs#L21) contains only one ".md"
`helpLinkUri: "https://github.com/Vannevelj/SharpSource/blob/master/docs/SS054-NewtonsoftMixedWithSystemTextJson.md");`

**Comment by Vannevelj** [comment]
Thanks! I've fixed this
