### ISSUE TITLE
SS049 false positive: symbol == symbol.ToUpper()

### ISSUE THREAD

**Issue by genxs-trading** [Vannevelj/SharpSource#324]
`bool isAllCaps = symbol == symbol.ToUpper();`

Comparing a string to its own `ToUpper` to test whether the string was already all uppercase or not, should not trigger `SS049`. Or at least not suggest this fix:

`string.Equals(symbol, symbol, StringComparison.InvariantCultureIgnoreCase)` as that is not functionally the same.

Probably out of scope for this analyzer, but a few nice suggestions are listed on stackoverflow. I opted for `symbol.All(char.IsUpper)`

https://stackoverflow.com/questions/448206/detecting-if-a-string-is-all-caps/448225#448225

**Comment by Vannevelj** [comment]
Thanks for flagging this! I've opted to not trigger the analyzer altogether when the same symbol is used in both operands. I expect it will be a pretty rare scenario to encounter.

This will become available in a few minutes after https://github.com/Vannevelj/SharpSource/pull/327 is merged.
