### ISSUE TITLE
Warnings raised in auto-generated files from .NET MAUI

### ISSUE THREAD

**Issue by tschbc** [Vannevelj/SharpSource#348]
SharpSource raises warnings about auto-generated code from the .NET MAUI framework:

![image](https://github.com/Vannevelj/SharpSource/assets/107572690/4f0254d9-f9d2-4b6c-8beb-3cfc324b23d5)

This screenshot is from a freshly-created project in Visual Studio 17.8.6—the only change made was to add a PackageReference to SharpSource.

My expected behaviour is that SharpSource would ignore auto-generated code.

**Comment by Vannevelj** [comment]
I agree, that doesn't seem particularly valuable. I'm a bit in two minds because of the prevalence of source generators these days but I don't think weighs up against the trade-off here. I'll remove generated code analysis from all analysers

**Comment by Vannevelj** [comment]
@tschbc I've published a new version. Give it a try and let me know how that goes!

**Comment by tschbc** [comment]
That was impressively fast! I'll give it a shot now.

**Comment by tschbc** [comment]
I can confirm that I'm no longer seeing any warnings from auto-generated files.

Thank you!
