### ISSUE TITLE
Add diagnostic on .Distinct() calls in ElementaryMethodsOfTypeInCollectionNotOverridden 

### ISSUE THREAD

**Issue by Advitalitum** [Vannevelj/SharpSource#356]
Hi.
I suggest to add diagnostic on `collectionWithTypeNonOverridden.Distinct()` calls in [ElementaryMethodsOfTypeInCollectionNotOverridden](https://github.com/Vannevelj/SharpSource/blob/9546e54d6c1b8eea3eb860474fb1a70621a425bf/SharpSource/SharpSource/Diagnostics/ElementaryMethodsOfTypeInCollectionNotOverriddenAnalyzer.cs#L15).

I will make PR later if it's ok.

**Comment by Vannevelj** [comment]
Makes sense to me, go for it 👍
