### ISSUE TITLE
Inefficient LINQ projections

### ISSUE THREAD

**Issue by Vannevelj** [Vannevelj/SharpSource#4]
```csharp
.Select().Take()
.Select().Skip()
.Select().TakeWhile()
.Select().SkipWhile()
.Select().First()
.Select().Single()
.Select().Last()
.Select().FirstOrDefault()
.Select().SingleOrDefault()
.Select().LastOrDefault()
```

Closely related to https://github.com/Vannevelj/VSDiagnostics/issues/645

**Comment by Hosch250** [comment]
Not sure how this is inefficient since Linq is lazily executed?

**Comment by Vannevelj** [comment]
You're right, this doesn't seem correct. I'll close this issue and add `.Select()` as a case to the other issue -- I think that's where the confusion comes from.
