### ISSUE TITLE
SS004 Warning on System Types/Enums

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/SharpSource#62]
Trigger:
```
public static readonly Dictionary<DataType, string[]> DisplayOptions = new Dictionary<DataType, string[]>
{
    [DataType.Text] = new[] { "text", "multiline-text", "select" },
    [DataType.Integer] = new[] { "number", "select" },
    [DataType.Decimal] = new[] { "number", "select" },
    [DataType.DateTime] = new[] { "datetime", "select" },
    [DataType.Boolean] = new[] { "radio" }
};
```

`DataType` is an `enum`. `string[]` is obviously a system type. The warnings I get are:

| Severity | Code | Description |
|:-|:-|:-|
| Warning | SS004 | Implement Equals() and GetHashCode() methods of type DataType for use in a collection. |
| Warning | SS004 | Implement Equals() and GetHashCode() methods of type  for use in a collection. |

**Comment by Vannevelj** [comment]
Fixed and released in 0.4.0 https://github.com/Vannevelj/SharpSource/releases/tag/v0.4.0
